# Generated by Django 3.1 on 2020-11-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWIE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='img',
            field=models.ImageField(upload_to='static/Input/'),
        ),
    ]
