# Generated by Django 3.1 on 2020-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWIE', '0002_auto_20201120_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
