# Generated by Django 3.1 on 2020-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWIE', '0003_auto_20201120_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='img',
            field=models.ImageField(upload_to='UWIE/static/Input/'),
        ),
    ]
