# Generated by Django 3.1 on 2021-04-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWIE', '0004_auto_20201120_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCLAHE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UWIE/static/Input/CLAHE/')),
            ],
        ),
        migrations.DeleteModel(
            name='Input',
        ),
    ]
