# Generated by Django 3.1 on 2021-05-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWIE', '0005_auto_20210416_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UWIE/static/Input/DCP/')),
            ],
        ),
        migrations.CreateModel(
            name='InputMIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UWIE/static/Input/MIP/')),
            ],
        ),
        migrations.CreateModel(
            name='InputRAY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UWIE/static/Input/RAY/')),
            ],
        ),
    ]
