# Generated by Django 3.2.3 on 2021-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWIE', '0006_inputdcp_inputmip_inputray'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UWIE/static/Input/CLASSIFY/')),
            ],
        ),
    ]
