# Generated by Django 3.2.3 on 2021-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWIE', '0007_inputclassify'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputRGHS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UWIE/static/Input/RGHS/')),
            ],
        ),
    ]
