# Generated by Django 3.2.3 on 2021-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWIE', '0008_inputrghs'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputULAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='UWIE/static/Input/ULAP/')),
            ],
        ),
    ]
